[config]
colors = false # not yet implemented
parallel-downloads = 3 # same as colors

[mirrors]
trust-level = "low"

[mirrors.main]
server = "https://example.com"
trust-level.override = "medium" # verify only repo, not packages.
